kind: batch
tasks:
  - strategy:
      matrix:
        lr: [100, 10, 1]
        ratio: [2, 4]
    image: ubuntu
    preset: cpu-small
    bash: |
      echo "Train lr=${{ matrix.lr}} ratio=${{ matrix.ratio }}"
      sleep 3
      echo ::set-output name=acc::0.93
